"""Initial migration

Revision ID: 018e5d9ab2f3
Revises: 
Create Date: 2024-11-23 00:44:56.744268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018e5d9ab2f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('FREE', 'PREMIUM', 'ADMIN', name='userrole'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('file_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=True),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(), nullable=True),
    sa.Column('file_hash', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_path')
    )
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_metadata_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_file_metadata_id'), ['id'], unique=False)

    op.create_table('translation_tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('source_language', sa.String(length=10), nullable=False),
    sa.Column('target_language', sa.String(length=10), nullable=False),
    sa.Column('service', sa.Enum('GOOGLE', 'DEEPL', name='translationservice'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='translationstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('character_count', sa.Integer(), nullable=False),
    sa.Column('result_file_id', sa.Integer(), nullable=True),
    sa.Column('task_metadata', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['file_metadata.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['result_file_id'], ['file_metadata.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_tasks_id'), ['id'], unique=False)

    op.create_table('translation_segments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('segment_index', sa.Integer(), nullable=False),
    sa.Column('original_text', sa.String(), nullable=False),
    sa.Column('translated_text', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='translationstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('segment_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['translation_tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_segments_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_segments_id'))

    op.drop_table('translation_segments')
    with op.batch_alter_table('translation_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_tasks_id'))

    op.drop_table('translation_tasks')
    with op.batch_alter_table('file_metadata', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_metadata_id'))
        batch_op.drop_index(batch_op.f('ix_file_metadata_filename'))

    op.drop_table('file_metadata')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    # ### end Alembic commands ###
