"""add_translation_system_tables

Revision ID: 6d1dd08e227b
Revises: 283b9ca95921
Create Date: 2024-11-27 01:00:56.446284

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d1dd08e227b"
down_revision: Union[str, None] = "283b9ca95921"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "epub_files",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("file_size", sa.Integer(), nullable=False),
        sa.Column("original_filename", sa.String(), nullable=False),
        sa.Column("upload_date", sa.DateTime(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_epub_files_id"), "epub_files", ["id"], unique=False)
    op.create_table(
        "translation_projects",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("epub_file_id", sa.Integer(), nullable=False),
        sa.Column("source_language", sa.String(length=10), nullable=False),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "PAUSED",
                name="translationstatus",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("total_words", sa.Integer(), nullable=True),
        sa.Column("translated_words", sa.Integer(), nullable=True),
        sa.Column("total_cost", sa.Float(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["epub_file_id"],
            ["epub_files.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translation_projects_id"), "translation_projects", ["id"], unique=False
    )
    op.create_table(
        "cost_records",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "cost_type",
            sa.Enum(
                "TRANSLATION",
                "VALIDATION",
                "MEMORY_LOOKUP",
                "API_CALL",
                "STORAGE",
                name="costtype",
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("usage_metrics", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["translation_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_cost_records_id"), "cost_records", ["id"], unique=False)
    op.create_table(
        "translation_chunks",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("sequence_number", sa.Integer(), nullable=False),
        sa.Column("content_type", sa.String(length=50), nullable=False),
        sa.Column("original_content", sa.Text(), nullable=False),
        sa.Column("translated_content", sa.Text(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "IN_PROGRESS",
                "COMPLETED",
                "FAILED",
                "VERIFIED",
                name="chunkstatus",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("word_count", sa.Integer(), nullable=True),
        sa.Column("token_count", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["translation_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translation_chunks_id"), "translation_chunks", ["id"], unique=False
    )
    op.create_table(
        "translation_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column(
            "progress_type",
            sa.Enum(
                "INITIALIZATION",
                "PROCESSING",
                "TRANSLATION",
                "VALIDATION",
                "ASSEMBLY",
                "ERROR",
                name="progresstype",
            ),
            nullable=False,
        ),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("details", sa.JSON(), nullable=True),
        sa.Column("chunks_total", sa.Integer(), nullable=True),
        sa.Column("chunks_completed", sa.Integer(), nullable=True),
        sa.Column("words_total", sa.Integer(), nullable=True),
        sa.Column("words_completed", sa.Integer(), nullable=True),
        sa.Column("estimated_remaining_time", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["translation_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_translation_progress_id"), "translation_progress", ["id"], unique=False
    )
    op.create_table(
        "translation_memory",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.Integer(), nullable=False),
        sa.Column("chunk_id", sa.Integer(), nullable=True),
        sa.Column("source_text", sa.Text(), nullable=False),
        sa.Column("translated_text", sa.Text(), nullable=False),
        sa.Column("source_language", sa.String(length=10), nullable=False),
        sa.Column("target_language", sa.String(length=10), nullable=False),
        sa.Column("context_key", sa.String(length=255), nullable=True),
        sa.Column("similarity_key", sa.String(length=255), nullable=True),
        sa.Column("quality_score", sa.Float(), nullable=True),
        sa.Column("usage_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["chunk_id"],
            ["translation_chunks.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["translation_projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_memory_context", "translation_memory", ["context_key"], unique=False
    )
    op.create_index(
        "idx_memory_similarity", "translation_memory", ["similarity_key"], unique=False
    )
    op.create_index(
        "idx_memory_source_target",
        "translation_memory",
        ["source_language", "target_language"],
        unique=False,
    )
    op.create_index(
        op.f("ix_translation_memory_id"), "translation_memory", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_translation_memory_id"), table_name="translation_memory")
    op.drop_index("idx_memory_source_target", table_name="translation_memory")
    op.drop_index("idx_memory_similarity", table_name="translation_memory")
    op.drop_index("idx_memory_context", table_name="translation_memory")
    op.drop_table("translation_memory")
    op.drop_index(op.f("ix_translation_progress_id"), table_name="translation_progress")
    op.drop_table("translation_progress")
    op.drop_index(op.f("ix_translation_chunks_id"), table_name="translation_chunks")
    op.drop_table("translation_chunks")
    op.drop_index(op.f("ix_cost_records_id"), table_name="cost_records")
    op.drop_table("cost_records")
    op.drop_index(op.f("ix_translation_projects_id"), table_name="translation_projects")
    op.drop_table("translation_projects")
    op.drop_index(op.f("ix_epub_files_id"), table_name="epub_files")
    op.drop_table("epub_files")
    # ### end Alembic commands ###
